### ISSUE TITLE
NFM S7 V3 crashes during stage 5 game highlight

### ISSUE THREAD

**Issue by Adnan2k** [shachar700/NFM-S7-Pack#1]
When I'm playing Need for Madness S7 V3, if I get wasted at or complete stage 5 (Charlie and the Chocolate Factory), the game crashes during the game highlight. I don't know if it's my computer, but S7 and S7 V2 work fine without any crashes.

**Comment by shachar700** [comment]
I just tested it and it works fine for me. Try Java 8 runtime
![Screenshot_322](https://github.com/user-attachments/assets/7a7008d0-c17c-4399-9b35-e93d35d1e90c)

**Comment by Adnan2k** [comment]
I do have Java 8 runtime, I think it's update 208

**Comment by Adnan2k** [comment]
I tried again, and the game doesn't crash this time.
